version: "2"

services:
  # The main server (node.js) instance
  simulator:
    container_name: simulator

    # Use Dockerfile for build commands
    build: ./docker/server

    # Expose ports
    ports:
      - "5000:5000"

    # Link with mongo service
    links:
      - sim_mongo
      - sim_redis

    environment:
      - MONGO_URL=mongodb://sim_mongo:27017/simulator-db
      - FLASK_APP=/app/server.py
      - FLASK_DEBUG=1
      - REDIS_URL=redis://sim_redis:6379/0

    # Mount the project directory to the container's directory for hot reloading.
    volumes:
      - .:/app

  # The mongodb instance
  sim_mongo:
    container_name: sim_mongo

    # Use the official mongo image
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  sim_redis:
    container_name: sim_redis
    image: redis:4.0
    ports:
      - "6379:6379"

  celery:
    build: ./docker/celery
    command: celery worker -A app --loglevel=DEBUG
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://sim_mongo:27017/simulator-db
      - REDIS_URL=redis://sim_redis:6379/0
      - PATH=$PATH:/app/simulators/bear/scripts
    links:
      - sim_redis
      - sim_mongo
