version: "2"

services:
  # The main server (node.js) instance
  server:
    container_name: server

    # Use Dockerfile for build commands
    build: ./docker/server

    # Expose ports
    ports:
      - "8284:8284"

    # Link with mongo service
    links:
      - sim_mongo
      - sim_redis

    environment:
      - MONGO_URL=mongodb://sim_mongo:27018/simulator-db
      - FLASK_APP=/app/server.py
      - FLASK_DEBUG=1
      - REDIS_URL=redis://sim_redis:6379/0
      - OMNINGSSIMULATOR_EMAIL=${OMNINGSSIMULATOR_EMAIL}
      - OMNINGSSIMULATOR_EMAIL_PW=${OMNINGSSIMULATOR_EMAIL_PW}
      - PROD_ENV=1

    # Mount the project directory to the container's directory for hot reloading.
    volumes:
      - .:/app

  # The mongodb instance
  sim_mongo:
    container_name: sim_mongo

    # Use the official mongo image
    image: mongo
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"

  sim_redis:
    container_name: sim_redis
    image: redis:4.0
    ports:
      - "6379:6379"

  celery:
    build: ./docker/celery
    command: celery worker -A app --loglevel=DEBUG
    volumes:
      - .:/app
    environment:
      - MONGO_URL=mongodb://sim_mongo:27018/simulator-db
      - REDIS_URL=redis://sim_redis:6379/0
    links:
      - sim_redis
      - sim_mongo
