#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 input
# $2 output directory
# $3       -d INT        outer distance between the two ends for pairs                          [500]
# $4       -s INT        standard deviation of the distance for pairs                           [50.000]
# $5       -C FLOAT      mean coverage across available positions (-1 to disable)               [100.00]
# $6       -r FLOAT      rate of mutations                                                      [0.0010]
# $7       -F FLOAT      frequency of given mutation to simulate low fequency somatic mutations [0.5000]
#                            NB: freqeuncy F refers to the first strand of mutation, therefore mutations 
#                            on the second strand occour with a frequency of 1-F 
# $8       -R FLOAT      fraction of mutations that are indels                                  [0.10]
# $9       -X FLOAT      probability an indel is extended                                       [0.30]
# $10      -I INT        the minimum length indel                                               [1]
# $11      -y FLOAT      probability of a random DNA read                                       [0.05]
# $12      -c INT        generate reads for                                                     [0]
#                            0: Illumina
#                            1: SOLiD
#                            2: Ion Torrent
# $13      -z INT        random seed (-1 uses the current time)                                 [-1]

dwgsim $1 $2 \
    -d $3 \
    -s $4 \
    -C $5 \
    -r $6 \
    -F $7 \
    -R $8 \
    -X $9 \
    -I $10 \
    -y $11 \
    -c $12 \
    -z $13 \
    2> /dev/null

tar -czf $2.tar \
    $2.bfast.fastq.gz \
    $2.bwa.read1.fastq.gz \
    $2.bwa.read2.fastq.gz \
    $2.mutations.vcf \
    $2.mutations.txt