#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 job id
# $2 input
# $3 output directory
# $4       -d INT        outer distance between the two ends for pairs                          [500]
# $5       -s INT        standard deviation of the distance for pairs                           [50.000]
# $6       -C FLOAT      mean coverage across available positions (-1 to disable)               [100.00]
# $7       -r FLOAT      rate of mutations                                                      [0.0010]
# $8       -F FLOAT      frequency of given mutation to simulate low fequency somatic mutations [0.5000]
#                            NB: freqeuncy F refers to the first strand of mutation, therefore mutations 
#                            on the second strand occour with a frequency of 1-F 
# $9       -R FLOAT      fraction of mutations that are indels                                  [0.10]
# $10       -X FLOAT      probability an indel is extended                                       [0.30]
# $11      -I INT        the minimum length indel                                               [1]
# $12      -y FLOAT      probability of a random DNA read                                       [0.05]
# $13      -c INT        generate reads for                                                     [0]
#                            0: Illumina
#                            1: SOLiD
#                            2: Ion Torrent
# $14      -z INT        random seed (-1 uses the current time)                                 [-1]

dwgsim $2 $3 \
    -d $4 \
    -s $5 \
    -C $6 \
    -r $7 \
    -F $8 \
    -R $9 \
    -X $10 \
    -I $11 \
    -y $12 \
    -c $13 \
    -z $14 \
    2> /dev/null

tar -czf $3.tar \
    $3.bfast.fastq.gz \
    $3.bwa.read1.fastq.gz \
    $3.bwa.read2.fastq.gz \
    $3.mutations.vcf \
    $3.mutations.txt