#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 job id
# $2 input reference
# $3 output
# -od <output_dir> | -output_dir <output_dir>

# $4 -tr <total_reads> | -total_reads <total_reads>
# Number of shotgun or amplicon reads to generate for each library. Do
# not specify this if you specify the fold coverage. Default: 100

# $5 -rd <read_dist>... | -read_dist <read_dist>...
# Desired shotgun or amplicon read length distribution specified as:
# average length, distribution ('uniform' or 'normal') and standard
# deviation.

# Only the first element is required. Examples:

# All reads exactly 101 bp long (Illumina GA 2x): 101
# Uniform read distribution around 100+-10 bp: 100 uniform 10
# Reads normally distributed with an average of 800 and a standard deviation of 100
# bp (Sanger reads): 800 normal 100
# Reads normally distributed with an average of 450 and a standard deviation of 50
# bp (454 GS-FLX Ti): 450 normal 50

# Reference sequences smaller than the specified read length are not
# used. Default: 100

# $6 -id <insert_dist>... | -insert_dist <insert_dist>...
# Create paired-end or mate-pair reads spanning the given insert
# length. Important: the insert is defined in the biological sense,
# i.e. its length includes the length of both reads and of the stretch
# of DNA between them: 0 : off, or: insert size distribution in bp, in
# the same format as the read length distribution (a typical value is
# 2,500 bp for mate pairs) Two distinct reads are generated whether or
# not the mate pair overlaps. Default: 0

# $7 -mo <mate_orientation> | -mate_orientation <mate_orientation>
# When generating paired-end or mate-pair reads (see <insert_dist>),
# specify the orientation of the reads (F: forward, R: reverse):

# FR:  ---> <---  e.g. Sanger, Illumina paired-end, IonTorrent mate-pair
# FF:  ---> --->  e.g. 454
# RF:  <--- --->  e.g. Illumina mate-pair
# RR:  <--- <---

# Default: FR

# $8 -un <unidirectional> | -unidirectional <unidirectional>
# Instead of producing reads bidirectionally, from the reference
# strand and its reverse complement, proceed unidirectionally, from
# one strand only (forward or reverse). Values: 0 (off, i.e.
# bidirectional), 1 (forward), -1 (reverse). Use <unidirectional> = 1
# for amplicon and strand-specific transcriptomic or proteomic
# datasets. Default: 0

# $9 -lb <length_bias> | -length_bias <length_bias>
# In shotgun libraries, sample reference sequences proportionally to
# their length. For example, in simulated microbial datasets, this
# means that at the same relative abundance, larger genomes contribute
# more reads than smaller genomes (and all genomes have the same fold
# coverage). 0 = no, 1 = yes. Default: 1

# $10 -cb <copy_bias> | -copy_bias <copy_bias>
# In amplicon libraries where full genomes are used as input, sample
# species proportionally to the number of copies of the target gene:
# at equal relative abundance, genomes that have multiple copies of
# the target gene contribute more amplicon reads than genomes that
# have a single copy. 0 = no, 1 = yes. Default: 1

# $11 -rs <random_seed> | -random_seed <random_seed>
# Seed number to use for the pseudo-random number generator.

# $12 -dt <desc_track> | -desc_track <desc_track>
# Track read information (reference sequence, position, errors, ...)
# by writing it in the read description. Default: 1

interpolated_command="\"grinder -rf $2 -od $3 -tr $4 -rd $5 -id $6 -mo $7 -un $8 -lb $9 -cb ${10} -rs ${11} -dt ${12}\""
ssh vincentl@newriver1.arc.vt.edu "/home/vincentl/omni-ngs-simulator/arc/update.sh 1 ${1} ${interpolated_command}"

grinder -rf $2 -od $3 \
    -tr $4 \
    -rd $5 \
    -id $6 \
    -mo $7 \
    -un $8 \
    -lb $9 \
    -cb ${10} \
    -rs ${11} \
    -dt ${12}


tar -czf $3.tar.gz -C /work/newriver/vincentl/omningssimulator/${1} .
ssh vincentl@newriver1.arc.vt.edu "/home/vincentl/omni-ngs-simulator/arc/update.sh 2 ${1}"