#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 job id
# $2 arc user
# $3 input
# $4 output
# $5 -s, --seed INT
#       The seed for Rng. Default: 0.
# $6 -N, --num-reads NUM
#       Number of reads (or mate pairs) to simulate. Default: 1000.

# $7 -sn, --source-length NUM
#       Length of random source sequence. Default: 1000000.

# $8 -spA, --source-probability-A NUM
#       Propabilibty for A in randomly generated sequence. Default: 0.25.
# $9 -spC, --source-probability-C NUM
#       Propabilibty for C in randomly generated sequence. Default: 0.25.
# $10 -spG, --source-probability-G NUM
#       Propabilibty for G in randomly generated sequence. Default: 0.25.

# Sanger Error Model Parameters:
# $11   -pmb, --probability-mismatch-begin NUM
#         Probability for a mismatch at begin of read. Default: 0.005.
# $12  -pme, --probability-mismatch-end NUM
#         Probability for a mismatch at end of read. Default: 0.01.
# $13  -pib, --probability-insert-begin NUM
#         Probability for a insert at begin of read. Default: 0.0025.
# $14  -pie, --probability-insert-end NUM
#         Probability for a insert at end of read. Default: 0.005.
# $15  -pdb, --probability-delete-begin NUM
#         Probability for a delete at begin of read. Default: 0.0025.
# $16  -pde, --probability-delete-end NUM
#         Probability for a delete at end of read. Default: 0.005.

interpolated_command="\"mason sanger --seed $5 --num-reads $6 --source-length $7 --source-probability-A $8 --source-probability-C $9 --source-probability-G ${10} --pmb ${11} --pme ${12} --pib ${13} --pie ${14} --pdb ${15} --pde ${16} input -o output\""
ssh ${2}@newriver1.arc.vt.edu "/groups/ngsproj/omni-ngs-simulator/arc/update.sh 1 ${1} ${interpolated_command}"

mason sanger \
    --seed $5 \
    --num-reads $6 \
    --source-length $7 \
    --source-probability-A $8 \
    --source-probability-C $9 \
    --source-probability-G ${10} \
    --pmb ${11} \
    --pme ${12} \
    --pib ${13} \
    --pie ${14} \
    --pdb ${15} \
    --pde ${16} \
    $3 -o $4.fasta
    
tar -czf $4.tar.gz -C /groups/ngsproj/generated_data/${1} .
ssh ${2}@newriver1.arc.vt.edu "/groups/ngsproj/omni-ngs-simulator/arc/update.sh 2 ${1}"
