#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Use 'random.fasta' for the SEQUENCE file name to generate it randomly.

# Arguments
# $1 input
# $2 output
# $3 -s, --seed INT
#       The seed for Rng. Default: 0.
# $4 -N, --num-reads NUM
#       Number of reads (or mate pairs) to simulate. Default: 1000.

# $5 -sn, --source-length NUM
#       Length of random source sequence. Default: 1000000.

# $6 -spA, --source-probability-A NUM
#       Propabilibty for A in randomly generated sequence. Default: 0.25.
# $7 -spC, --source-probability-C NUM
#       Propabilibty for C in randomly generated sequence. Default: 0.25.
# $8 -spG, --source-probability-G NUM
#       Propabilibty for G in randomly generated sequence. Default: 0.25.

# Illumina Error Model:
# $9 -pi, --prob-insert NUM
#       Probability of an insertion. Default: 0.001.
# $10 -pd, --prob-delete NUM
#       Probability of a deletion. Default: 0.001.
# $11 -pmm, --prob-mismatch NUM
#       Average mismatch probability. Default: 0.004.
# $12 -pmmb, --prob-mismatch-begin NUM
#       Probability of a mismatch at the first base. Default: 0.002.
# $13 -pmme, --prob-mismatch-end NUM
#       Probability of a mismatch at the last base. Default: 0.012.

mason illumina \
    --seed $3 \
    --num-reads $4 \
    --source-length $5 \
    --source-probability-A $6 \
    --source-probability-C $7 \
    --source-probability-G $8 \
    --prob-insert $9 \
    --prob-delete $10 \
    --prob-mismatch $11 \
    --prob-mismatch-begin $12 \
    --prob-mismatch-end $13 \
    $1 -o $2.fasta

tar -czf $2.tar.gz $2.fasta