#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 job id
# $2 input
# $3 output
# $4 -s, --seed INT
#       The seed for Rng. Default: 0.
# $5 -N, --num-reads NUM
#       Number of reads (or mate pairs) to simulate. Default: 1000.

# $6 -sn, --source-length NUM
#       Length of random source sequence. Default: 1000000.

# $7 -spA, --source-probability-A NUM
#       Propabilibty for A in randomly generated sequence. Default: 0.25.
# $8 -spC, --source-probability-C NUM
#       Propabilibty for C in randomly generated sequence. Default: 0.25.
# $9 -spG, --source-probability-G NUM
#       Propabilibty for G in randomly generated sequence. Default: 0.25.

# Sanger Error Model Parameters:
# $10   -pmb, --probability-mismatch-begin NUM
#         Probability for a mismatch at begin of read. Default: 0.005.
# $11  -pme, --probability-mismatch-end NUM
#         Probability for a mismatch at end of read. Default: 0.01.
# $12  -pib, --probability-insert-begin NUM
#         Probability for a insert at begin of read. Default: 0.0025.
# $13  -pie, --probability-insert-end NUM
#         Probability for a insert at end of read. Default: 0.005.
# $14  -pdb, --probability-delete-begin NUM
#         Probability for a delete at begin of read. Default: 0.0025.
# $15  -pde, --probability-delete-end NUM
#         Probability for a delete at end of read. Default: 0.005.

interpolated_command="\"mason sanger --seed $4 --num-reads $5 --source-length $6 --source-probability-A $7 --source-probability-C $8 --source-probability-G $9 --pmb ${10} --pme ${11} --pib ${12} --pie ${13} --pdb ${14} --pde ${15} input -o output\""
ssh vincentl@newriver1.arc.vt.edu "/home/vincentl/omni-ngs-simulator/arc/update.sh 1 ${1} ${interpolated_command}"

mason sanger \
    --seed $4 \
    --num-reads $5 \
    --source-length $6 \
    --source-probability-A $7 \
    --source-probability-C $8 \
    --source-probability-G $9 \
    --pmb ${10} \
    --pme ${11} \
    --pib ${12} \
    --pie ${13} \
    --pdb ${14} \
    --pde ${15} \
    $2 -o $3.fasta
    
cd /work/newriver/vincentl/omningssimulator/${1}
tar -czf $3.tar.gz $3.fasta
ssh vincentl@newriver1.arc.vt.edu "/home/vincentl/omni-ngs-simulator/arc/update.sh 2 ${1}"