#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 input
# $2 output
# $3 -s, --seed INT
#       The seed for Rng. Default: 0.
# $4 -N, --num-reads NUM
#       Number of reads (or mate pairs) to simulate. Default: 1000.

# $5 -sn, --source-length NUM
#       Length of random source sequence. Default: 1000000.

# $6 -spA, --source-probability-A NUM
#       Propabilibty for A in randomly generated sequence. Default: 0.25.
# $7 -spC, --source-probability-C NUM
#       Propabilibty for C in randomly generated sequence. Default: 0.25.
# $8 -spG, --source-probability-G NUM
#       Propabilibty for G in randomly generated sequence. Default: 0.25.

# Sanger Error Model Parameters:
# $9   -pmb, --probability-mismatch-begin NUM
#         Probability for a mismatch at begin of read. Default: 0.005.
# $10  -pme, --probability-mismatch-end NUM
#         Probability for a mismatch at end of read. Default: 0.01.
# $11  -pib, --probability-insert-begin NUM
#         Probability for a insert at begin of read. Default: 0.0025.
# $12  -pie, --probability-insert-end NUM
#         Probability for a insert at end of read. Default: 0.005.
# $13  -pdb, --probability-delete-begin NUM
#         Probability for a delete at begin of read. Default: 0.0025.
# $14  -pde, --probability-delete-end NUM
#         Probability for a delete at end of read. Default: 0.005.

mason sanger \
    --seed $3 \
    --num-reads $4 \
    --source-length $5 \
    --source-probability-A $6 \
    --source-probability-C $7 \
    --source-probability-G $8 \
    --pmb $9 \
    --pme $10 \
    --pib $11 \
    --pie $12 \
    --pdb $13 \
    --pde $14 \
    $1 -o $2.fasta
    
tar -czf $2.tar.gz $2.fasta