#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Use 'random.fasta' for the SEQUENCE file name to generate it randomly.

# Arguments
# $1 job id
# $2 arc user
# $3 input
# $4 output
# $5 -s, --seed INT
#       The seed for Rng. Default: 0.
# $6 -N, --num-reads NUM
#       Number of reads (or mate pairs) to simulate. Default: 1000.

# $7 -sn, --source-length NUM
#       Length of random source sequence. Default: 1000000.

# $8 -spA, --source-probability-A NUM
#       Propabilibty for A in randomly generated sequence. Default: 0.25.
# $9 -spC, --source-probability-C NUM
#       Propabilibty for C in randomly generated sequence. Default: 0.25.
# $10 -spG, --source-probability-G NUM
#       Propabilibty for G in randomly generated sequence. Default: 0.25.

# Illumina Error Model:
# $11 -pi, --prob-insert NUM
#       Probability of an insertion. Default: 0.001.
# $12 -pd, --prob-delete NUM
#       Probability of a deletion. Default: 0.001.
# $13 -pmm, --prob-mismatch NUM
#       Average mismatch probability. Default: 0.004.
# $14 -pmmb, --prob-mismatch-begin NUM
#       Probability of a mismatch at the first base. Default: 0.002.
# $15 -pmme, --prob-mismatch-end NUM
#       Probability of a mismatch at the last base. Default: 0.012.

interpolated_command="\"mason illumina --seed $5 --num-reads $6 --source-length $7 --source-probability-A $8 --source-probability-C $9 --source-probability-G ${10} --prob-insert ${11} --prob-delete ${12} --prob-mismatch ${13} --prob-mismatch-begin ${14} --prob-mismatch-end ${15} input -o output\""
ssh ${2}@newriver1.arc.vt.edu "/groups/ngsproj/omni-ngs-simulator/arc/update.sh 1 ${1} ${interpolated_command}"

mason illumina \
    --seed $5 \
    --num-reads $6 \
    --source-length $7 \
    --source-probability-A $8 \
    --source-probability-C $9 \
    --source-probability-G ${10} \
    --prob-insert ${11} \
    --prob-delete ${12} \
    --prob-mismatch ${13} \
    --prob-mismatch-begin ${14} \
    --prob-mismatch-end ${15} \
    $3 -o $4.fasta

tar -czf $4.tar.gz -C /groups/ngsproj/generated_data/${1} .
ssh ${2}@newriver1.arc.vt.edu "/groups/ngsproj/omni-ngs-simulator/arc/update.sh 2 ${1}"
