#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A xwwugroup
#PBS -W group_list=ngsproj

# Arguments
# $1 job id
# $2 arc user
# $3 input reference
# $4 output

# $5 --length-min         minimum length (100).
# $6 --length-max         maximum length (CLR: 25000, CCS: 2500).
# $7 --accuracy-min       minimum accuracy.
                   # (CLR: 0.75, CCS: fixed as 0.75).
                   # this option can be used only in case of CLR.
# $8 --accuracy-max       maximum accuracy.
                   # (CLR: 1.00, CCS: fixed as 1.00).
                   # this option can be used only in case of CLR.
# $9:$10:$11 --difference-ratio   ratio of differences. substitution:insertion:deletion.
                   # each value up to 1000 (CLR: 10:60:30, CCS:6:21:73).
# $12 --seed               for a pseudorandom number generator (Unix time).
# $13 fastq file to sample

interpolated_command="\"pbsim --length-min $5 --length-max $6 --accuracy-min $7 --accuracy-max $8 --difference-ratio $9:${10}:${11} --seed ${12} --prefix output --sample-fastq fastq input\""
ssh ${2}@newriver1.arc.vt.edu "/groups/ngsproj/omni-ngs-simulator/arc/update.sh 1 ${1} ${interpolated_command}"

pbsim \
    --length-min $5 \
    --length-max $6 \
    --accuracy-min $7 \
    --accuracy-max $8 \
    --difference-ratio $9:${10}:${11} \
    --seed ${12} \
    --prefix $4 \
    --sample-fastq ${13} \
    $3


tar -czf $4.tar.gz -C /groups/ngsproj/generated_data/${1} .
ssh ${2}@newriver1.arc.vt.edu "/groups/ngsproj/omni-ngs-simulator/arc/update.sh 2 ${1}"