#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 job id
# $2 input reference
# $3 output

# $4 --length-min         minimum length (100).
# $5 --length-max         maximum length (CLR: 25000, CCS: 2500).
# $6 --accuracy-min       minimum accuracy.
                   # (CLR: 0.75, CCS: fixed as 0.75).
                   # this option can be used only in case of CLR.
# $7 --accuracy-max       maximum accuracy.
                   # (CLR: 1.00, CCS: fixed as 1.00).
                   # this option can be used only in case of CLR.
# $8:$9:$10 --difference-ratio   ratio of differences. substitution:insertion:deletion.
                   # each value up to 1000 (CLR: 10:60:30, CCS:6:21:73).
# $11 --seed               for a pseudorandom number generator (Unix time).
# $12 fastq file to sample

interpolated_command="\"pbsim --length-min $4 --length-max $5 --accuracy-min $6 --accuracy-max $7 --difference-ratio $8:$9:$10 --seed $11 --prefix output --sample-fastq $12 input\""
ssh vincentl@newriver1.arc.vt.edu "/home/vincentl/omni-ngs-simulator/arc/update.sh 1 ${1} ${interpolated_command}"

pbsim \
    --length-min $4 \
    --length-max $5 \
    --accuracy-min $6 \
    --accuracy-max $7 \
    --difference-ratio $8:$9:$10 \
    --seed $11 \
    --prefix $3 \
    --sample-fastq $12 \
    $2


tar -czf $3.tar.gz $3_0001.fastq $3_0001.maf $3_0001.ref
ssh vincentl@newriver1.arc.vt.edu "/home/vincentl/omni-ngs-simulator/arc/update.sh 2 ${1}"