#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 job id
# NO INPUT FILE
# $2 output

# Main FASTQ options:
# $3 -t  <sequencingType>     type: 1=Roche-454, 2=Illumina, 3=ABI SOLiD, 4=Ion Torrent
# $4 -hf <headerFormat>       header format: 1=Length appendix, 2=Pair End
# $5 -n  <numberOfReads>      number of reads per file

# DNA options:
# $6,$7,$8,$9,$10  -f  <A>,<C>,<G>,<T>,<N>  symbols frequency
# $11             -rn <numberOfRepeats>    repeats: number (default: 0)
# $12             -ri <repeatsMinSize>     repeats: minimum size
# $13             -ra <repeatsMaxSize>     repeats: maximum size
# $14             -rm <mutationRate>       repeats: mutation frequency

# $15 -s  <seed>               generation seed

# Common usage:
#  ./XS -v -t 1 -i n=MySeq -ld 30:80 -n 20000 -qt=1 -qc 33,36,39:43 File
#  ./XS -v -ls 100 -n 10000 -eh -eo -es -edb -f 0.3,0.2,0.2,0.3,0.0 -rn 50 -ri 300 -ra 3000 -rm 0.1 File

interpolated_command="\"XS -t output -hf $4 -n $5 -f $6,$7,$8,$9,${10} -rn ${11} -ri ${12} -ra ${13} -rm ${14} -s ${15} input\""
ssh vincentl@newriver1.arc.vt.edu "/home/vincentl/omni-ngs-simulator/arc/update.sh 1 ${1} ${interpolated_command}"

XS \
    -t $3 \
    -hf $4 \
    -n $5 \
    -f $6,$7,$8,$9,${10} \
    -rn ${11} \
    -ri ${12} \
    -ra ${13} \
    -rm ${14} \
    -s ${15} \
    $2
    
cd /work/newriver/vincentl/omningssimulator/${1}
tar -czf $2.tar.gz $2
ssh vincentl@newriver1.arc.vt.edu "/home/vincentl/omni-ngs-simulator/arc/update.sh 2 ${1}"