#!/bin/bash

#PBS -l walltime=100:00:00
#PBS -q normal_q
#PBS -A cs4884s18
#PBS -W group_list=newriver

# Arguments
# $1 job id
# $2 arc user
# NO INPUT FILE
# $3 output

# Main FASTQ options:
# $4 -t  <sequencingType>     type: 1=Roche-454, 2=Illumina, 3=ABI SOLiD, 4=Ion Torrent
# $5 -hf <headerFormat>       header format: 1=Length appendix, 2=Pair End
# $6 -n  <numberOfReads>      number of reads per file

# DNA options:
# $7,$8,$9,$10,$11  -f  <A>,<C>,<G>,<T>,<N>  symbols frequency
# $12             -rn <numberOfRepeats>    repeats: number (default: 0)
# $13             -ri <repeatsMinSize>     repeats: minimum size
# $14             -ra <repeatsMaxSize>     repeats: maximum size
# $15             -rm <mutationRate>       repeats: mutation frequency

# $16 -s  <seed>               generation seed

# Common usage:
#  ./XS -v -t 1 -i n=MySeq -ld 30:80 -n 20000 -qt=1 -qc 33,36,39:43 File
#  ./XS -v -ls 100 -n 10000 -eh -eo -es -edb -f 0.3,0.2,0.2,0.3,0.0 -rn 50 -ri 300 -ra 3000 -rm 0.1 File

interpolated_command="\"XS -t $4 -hf $5 -n $6 -f $7,$8,$9,${10},${11} -rn ${12} -ri ${13} -ra ${14} -rm ${15} -s ${16} output\""
ssh ${2}@newriver1.arc.vt.edu "/groups/ngsproj/omni-ngs-simulator/arc/update.sh 1 ${1} ${interpolated_command}"

XS \
    -t $4 \
    -hf $5 \
    -n $6 \
    -f $7,$8,$9,${10},${11} \
    -rn ${12} \
    -ri ${13} \
    -ra ${14} \
    -rm ${15} \
    -s ${16} \
    $3
    
tar -czf $3.tar.gz -C /groups/ngsproj/generated_data/${1} .
ssh ${2}@newriver1.arc.vt.edu "/groups/ngsproj/omni-ngs-simulator/arc/update.sh 2 ${1}"